_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 25
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('sdac_train_base',)
  TEST: ('sdac_test_base',)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.001
  STEPS: (36000, )
  MAX_ITER: 100000
  CHECKPOINT_PERIOD: 50000
  WARMUP_ITERS: 10
OUTPUT_DIR: "checkpoints/sdac/base_v05_random_split/"
